x-common:
  panel:
    &panel-environment
    APP_URL: "https://localhost"
    APP_DEBUG: "true"
    ADMIN_EMAIL: "USEYOUROWNEMAILHERE@example.com"

    APP_ENVIRONMENT_ONLY: "false"
    APP_ENV: "production"
    SESSION_DRIVER: "file"

  mail:
    &mail-environment
    MAIL_DRIVER: "log"
    # MAIL_HOST: ""
    # MAIL_PORT: ""
    # MAIL_FROM: ""
    # MAIL_USERNAME: ""
    # MAIL_PASSWORD: ""
    # MAIL_ENCRYPTION: ""

services:
  caddy:
    image: caddy:2.8.4-alpine
    # image: ghcr.io/lutherlabs/panel:latest
    restart: always
    volumes:
      - pelican-data:/var/www/html/
      - pelican-logs:/var/www/html/storage/logs/
      - ./Caddyfile:/etc/caddy/Caddyfile
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    env_file:
      - ./.env.docker
    environment:
      <<: [*panel-environment, *mail-environment]
    logging:
      driver: "json-file"
      options:
        max-size: "1M"
        max-file: "10"
    command:
      - /bin/sh
      - -c
      - caddy run --config /etc/caddy/Caddyfile --adapter caddyfile
      # The sed replacement is a hack, Caddyfile should be updated to use Docker DNS.

  mariadb:
    image: mariadb
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: true
      MARIADB_USER: pelican
      MARIADB_PASSWORD: pelican
      MARIADB_DATABASE: pelican
    volumes:
      - pelican-data:/var/www/html/database
    healthcheck:
      interval: 5s
      test: ["CMD", "healthcheck.sh" ,"--connect", "--innodb_initialized"]
      retries: 5
      start_period: 5s
    restart: always
    ports:
      - "3306"

  panel: # Panel should only run php-fpm
    image: panel:latest
    depends_on:
      mariadb:
        condition: service_healthy
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - pelican-data:/var/www/html/
      - pelican-logs:/var/www/html/storage/logs/
    environment:
      <<: [*panel-environment, *mail-environment]
      DB_CONNECTION: mariadb
      DB_HOST: mariadb
      DB_PORT: 3306
      DB_DATABASE: pelican
      DB_USERNAME: pelican
      DB_PASSWORD: pelican
    command:
      - /bin/sh
      - -c
      - php-fpm

volumes:
  pelican-data:
  pelican-logs:

networks:
  default:
    ipam:
      config:
        - subnet: 172.20.0.0/16
